services:
  - type: web
    name: petstore-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    
  - type: web
    name: petstore-frontend
    env: static
    plan: free
    repo: https://github.com/henryyeoj/petstorefrontend
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: petstore-backend
          envVarKey: RENDER_EXTERNAL_URL
